### PR TITLE
Make src code compile on non-Windows

### PR DESCRIPTION
**Pull request by ibroheem**
Modified the _s family functions to be Linux/Unix -compatible, gcc at least

### CODE REVIEW

**Comment by jacking75** [comment]
The code is targeted to the Windows platform and can not be tampered with with the code used in the published book.  
  
If you want to support Linux, please create a new directory and upload your Linux platform target code.  
For example, '07_simple_TCPServer_linux' would be the name of the directory.

**Comment by lee-eon-seok** [comment]
thank you

**Comment by lee-eon-seok** [comment]
07_simple_tcpserver_unix

**Comment by lee-eon-seok** [comment]
07_simple_tcpserver_linux

**Comment by lee-eon-seok** [comment]
unix

**Pull request closed without merging**
